In [1]:
import pandas as pd

In [2]:
# Read csv file and display first 10 rows
pd.read_csv('PRODUCT.csv').head(10)

,Record_ID,Month,Product_Name,Category,Original_Price_USD,Discount_Percent,Effective_Price_USD,Ad_Expenditure_USD,Customer_Visits,Units_Sold,Total_Sales_USD,Gross_Profit_USD,Net_Profit_USD
0,1000,2025-04,Air Purifier Pro,Home Appliances,229.92,15,195.43,15568.47,23979,1947,380502.21,178136.33,162567.86
1,1001,2025-08,Wireless Noise-Canceling Headphones,Electronics,258.31,5,245.39,5772.89,10809,454,111407.06,52480.36,46707.47
2,1002,2025-01,Stainless Steel Air Fryer,Kitchen,130.32,5,123.80,2596.64,8277,519,64252.20,31229.14,28632.50
3,1003,2025-09,Ergonomic Desk Chair,Furniture,305.49,10,274.94,5507.32,8992,830,228200.20,89615.44,84108.12
4,1004,2025-10,Wireless Noise-Canceling Headphones,Electronics,245.12,0,245.12,17579.48,33147,731,179182.72,82257.05,64677.57
5,1005,2025-02,Ergonomic Desk Chair,Furniture,325.20,5,308.94,13721.60,27689,946,292257.24,123991.38,110269.78
6,1006,2025-12,Gaming Laptop Pro,Computers,1513.73,20,1210.98,15550.65,39239,2379,2880921.42,1162680.54,1147129.89
7,1007,2025-08,4K OLED Smart TV,Electronics,1182.81,5,1123.67,14253.36,21564,1616,1815850.72,941461.52,927208.16
8,1008,2025-09,Air Purifier Pro,Home Appliances,225.99,0,225.99,1629.77,6198,410,92655.90,50274.68,48644.91
9,1009,2025-10,Air Purifier Pro,Home Appliances,211.55,20,169.24,16147.51,28788,959,162301.16,64697.66,48550.15

In [3]:
# Read multi-sheet excel and access one specific sheet
pd.read_excel('company_data.xlsx',sheet_name='Employees')

  Employee_ID           Name Department  Salary_USD
0         E01    Alice Smith      Sales       75000
1         E02      Bob Jones         IT       82000
2         E03  Charlie Brown  Marketing       68000
3         E04   Diana Prince      Sales       78000
4         E05    Evan Wright         HR       62000

In [4]:
# Read json file and convert to table using json normalize
import json
with open('PRODUCT.json', 'r') as jsonfile:
    data = json.load(jsonfile)

pd.json_normalize(data)

,Record_ID,Month,Product_Name,Category,Original_Price_USD,Discount_Percent,Effective_Price_USD,Ad_Expenditure_USD,Customer_Visits,Units_Sold,Total_Sales_USD,Gross_Profit_USD,Net_Profit_USD
0,1000,2025-04,Air Purifier Pro,Home Appliances,229.92,15,195.43,15568.47,23979,1947,380502.21,178136.33,162567.86
1,1001,2025-08,Wireless Noise-Canceling Headphones,Electronics,258.31,5,245.39,5772.89,10809,454,111407.06,52480.36,46707.47
2,1002,2025-01,Stainless Steel Air Fryer,Kitchen,130.32,5,123.80,2596.64,8277,519,64252.20,31229.14,28632.50
3,1003,2025-09,Ergonomic Desk Chair,Furniture,305.49,10,274.94,5507.32,8992,830,228200.20,89615.44,84108.12
4,1004,2025-10,Wireless Noise-Canceling Headphones,Electronics,245.12,0,245.12,17579.48,33147,731,179182.72,82257.05,64677.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,1145,2025-04,Wireless Noise-Canceling Headphones,Electronics,237.95,15,202.26,8412.95,21827,2214,447803.64,200963.69,192550.74
146,1146,2026-02,Stainless Steel Air Fryer,Kitchen,125.03,0,125.03,17610.78,32964,786,98273.58,48331.23,30720.45
147,1147,2025-02,4K OLED Smart TV,Electronics,1235.71,5,1173.92,12197.67,16106,431,505959.52,245389.71,233192.04
148,1148,2025-11,Portable Bluetooth Speaker,Audio,90.74,20,72.59,19826.50,26329,1272,92334.48,29006.72,9180.22
149,1149,2025-06,Portable Bluetooth Speaker,Audio,86.42,5,82.10,19731.41,49797,1333,109439.30,51445.91,31714.50